#!/bin/csh -f

set args  = ()
set clean = 0

while ($#argv > 0)
  if ("$1" == "-clean") then
    set clean = 1
    shift
  else
    set args = ($args $1:q)
    shift
  endif
end

if ($clean == 1) then
  rm *_svg.h
endif

foreach file (*.svg)
  CBinArr -qsvg $file > $file:r_svg.h.1

  set copy = 0

  if (! -e $file:r_svg.h) then
    set copy = 1
  else
    cmp -s $file:r_svg.h.1 $file:r_svg.h

    if ($status != 0) then
      set copy = 1
    endif
  endif

  if ($copy == 1) then
    echo "Update $file:r_svg.h"

    cp $file:r_svg.h.1 $file:r_svg.h
  endif

  rm $file:r_svg.h.1
end

exit 0
